### ISSUE TITLE
This project does not contain necessary .dll files!

### ISSUE THREAD

**Issue by ArturMarekNowak** [Commentsareuseless/ProjektNaMatme#4]
This project does not contain necessary .dll files which are absolutely essential for this project to work. Please include them in next release! I'm calling @Commentsareuseless.

**Comment by Commentsareuseless** [comment]
This project is just "self containted" sources, it does not need any dlls :) 
I know that Code::Blocks by default links c++ std lib dynamicaly which is not an issue of this project. If you want static linking you need to change it in settings, this way you won't need any additional dlls
